// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPg3OaO5G-hqLFHjMUKXRdHO5tn5cCDc',
    appId: '1:669337409000:web:c5af18fe913f742640c05d',
    messagingSenderId: '669337409000',
    projectId: 'absensi-wajah-ed574',
    authDomain: 'absensi-wajah-ed574.firebaseapp.com',
    storageBucket: 'absensi-wajah-ed574.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExzGO-PysL2MV8f-VAaRQpdqOUhjuNS4',
    appId: '1:669337409000:android:7302eb237a97e83840c05d',
    messagingSenderId: '669337409000',
    projectId: 'absensi-wajah-ed574',
    storageBucket: 'absensi-wajah-ed574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFr7KusuCHxLI0VESHNvmcmZBwtH2ZTI',
    appId: '1:669337409000:ios:d9a35e64da5c887f40c05d',
    messagingSenderId: '669337409000',
    projectId: 'absensi-wajah-ed574',
    storageBucket: 'absensi-wajah-ed574.firebasestorage.app',
    iosBundleId: 'com.example.absensiFaceDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAFr7KusuCHxLI0VESHNvmcmZBwtH2ZTI',
    appId: '1:669337409000:ios:d9a35e64da5c887f40c05d',
    messagingSenderId: '669337409000',
    projectId: 'absensi-wajah-ed574',
    storageBucket: 'absensi-wajah-ed574.firebasestorage.app',
    iosBundleId: 'com.example.absensiFaceDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHPg3OaO5G-hqLFHjMUKXRdHO5tn5cCDc',
    appId: '1:669337409000:web:e02de5682af7d96340c05d',
    messagingSenderId: '669337409000',
    projectId: 'absensi-wajah-ed574',
    authDomain: 'absensi-wajah-ed574.firebaseapp.com',
    storageBucket: 'absensi-wajah-ed574.firebasestorage.app',
  );
}
